backend:
  name: github
  repo: hitsujimaya/testsienna
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "記事"
    folder: "src/content/post"
    create: true
    format: "frontmatter"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "publishDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD" }
      - { label: "説明文", name: "description", widget: "string" }
      - { label: "タグ", name: "tags", widget: "list", default: ["blog"] }
      - { label: "本文", name: "body", widget: "markdown" }
