backend:
  name: github
  repo: hitsujimaya/testsienna
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "記事"
    folder: "src/content/post" # ← Astro Siennaが記事を探す場所！
    create: true
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "説明文", name: "description", widget: "string", required: false }
      - { label: "公開日", name: "publishDate", widget: "datetime" }
      - { label: "本文", name: "body", widget: "markdown" }
